### ISSUE TITLE
Crash after Badeline chase sequence in Chapter 6

### ISSUE THREAD

**Issue by HunterBoy344** [MercuryWorkshop/celeste-wasm#2]
Upon moving into the room to the right after the chase sequence with Badeline ends and the music stops, the game crashes with the following error:

```
System.Exception: FMOD Failed: ERR_INVALID_HANDLE
     at Celeste.Level.LoadLevel(IntroTypes playerIntro, Boolean isFromLoader)
     at Celeste.Level.TransitionRoutine(LevelData next, Vector2 direction)+MoveNext()
     at Celeste.Level.Update()
     at Program.MainLoop()
```

This is not on the official instance, and I am hosting a copy myself.

**Comment by velzie** [comment]
This issue was fixed in the release builds a while ago but didn't get put into the repository itself, I'll try and see if i can push that within a couple days

**Comment by Stigstille** [comment]
@velzie bump!!

**Comment by velzie** [comment]
sorry lmao

**Comment by HunterBoy344** [comment]
Are you going to include these patches in a new release build? Right now only the first release is available

**Comment by velzie** [comment]
@HunterBoy344 look at what i said in the first comment, the first release always had the patch

**Comment by HunterBoy344** [comment]
> @HunterBoy344 look at what i said in the first comment, the first release always had the patch 

I am using the first release, specifically celeste-wasm.tar.zst from said release. That's where I ran into the issue to begin with

**Comment by velzie** [comment]
might have forgotten to update that one specifically then.. anyway I probably won't be updating *that* build since threads v2 is a thing now. uhhh @r58Playz are we gonna publish builds of that

**Comment by r58Playz** [comment]
https://celeste-threads.r58playz.dev/ has a build of threads-v2, threads-v2 doesn't need any extra source tars so building that is possible right now without releasing anything

**Comment by HunterBoy344** [comment]
If this threads-v2 build has the Badeline chase crash fixed, where can I download a copy of it?

I can't really use the official standalone HTML (long story) so I need a local copy of a build that's intended to run on a web server and has the Chapter 6 fix.

**Comment by r58Playz** [comment]
Legacy builds in the v0.9 release have been updated to fix the issue. threads-v2 builds are available via GitHub Actions/the latest continuous build release.
