### ISSUE TITLE
Unable to build to to privated/deleted submodule

### ISSUE THREAD

**Issue by CCF100** [MercuryWorkshop/celeste-wasm#3]
This project relies on the submodule in celeste/Celeste which is no longer publicly accessible...

**Comment by r58Playz** [comment]
See step 11 in the readme section "I want to build this".
You can also use genpatches.sh to apply the patches to a different decompilation.

**Comment by velzie** [comment]
yes this is intentional, we can't just publish celeste source code, instead omit --recursive when cloning and download the encrypted original source code zip in releases
